yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),

    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password/password_change_done.html'
        ),
        name='password_change_done'
    ),

    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler403 = 'core.views.csrf_failure'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


# В режиме DEBUG=True брать картинки из директории, указанной в MEDIA_ROOT
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/users/password/password_change_done.html
{% extends "users/base_users.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block heading %}Пароль изменён{% endblock %}
{% block result %}Пароль изменён успешно{% endblock %}

yatube/templates/users/password/password_change_form.html
{% extends "users/base_users.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block heading %}Изменить пароль{% endblock %}
{% block form %}
{% include 'users/includes/form.html' with button="Изменить пароль" %}
{% endblock %}

yatube/templates/users/password/password_reset_complete.html
{% extends "users/base_users.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block heading %}Восстановление пароля завершено{% endblock %}
{% block result %}Ваш пароль был сохранен. Используйте его для входа{% endblock %}
{% block link %}<a href="{% url 'users:login' %}">войти</a>{% endblock %}

yatube/templates/users/password/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
  {% if validlink %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Введите новый пароль
          </div>
          <div class="card-body">
            {% include 'users/includes/form.html' with button="Назначить новый пароль" %}
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  {% else %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Ошибка
          </div>
          <div class="card-body">
            <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  {% endif %}
{% endblock %}

yatube/templates/users/password/password_reset_done.html
{% extends "users/base_users.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block heading %}Отправлено письмо{% endblock %}
{% block result %}Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля{% endblock %}

yatube/templates/users/password/password_reset_form.html
{% extends "users/base_users.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block heading %}Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались{% endblock %}
{% block form %}
{% include 'users/includes/form.html' with button="Сбросить пароль" %}
{% endblock %}